### ISSUE TITLE
Support recursive file discovery

### ISSUE THREAD

**Issue by theandrewdavis** [tkruse/cpplint#4]
Hi! I've added a --recursive option to cpplint to allow it to find source files in nested directories, a feature that seems pretty widely desired based on my googling. Would you accept a pull request for this feature? I definitely understand if that is not your vision for this repo, but I wanted to try to avoid yet another fork on github and yet another pypi package name if possible.

**Comment by tkruse** [comment]
I sure can accept and make a new pypi release, or you might even consider aking over if you feel like maintaining cpplint. Does not seem like Google is doing a lot of maintenance.

**Comment by theandrewdavis** [comment]
Ok, great! I've just made a pull request. And sure, if you're looking for someone to take over maintenance, I'd be happy to.

**Comment by tkruse** [comment]
Handing over maintenance would be nice. Are you already set up at pypi?

**Comment by theandrewdavis** [comment]
I just created an account on pypi -- my username is also theandrewdavis. It looks like you can add me as a maintainer on pypi and I'll be able to submit updated packages.

**Comment by tkruse** [comment]
ok, added you as owner on Pypi. You can maintain and release as you like. I can only warn you of deleting releases on Pypi, once you deleted a version number, pypi does not allow you to re-release it.

Some other things to know:
You might want to get in touch with this guy:
https://github.com/tkruse/cpplint/issues/3

Also, Google has moved the Styleguides to github:
https://github.com/google/styleguide/
And cpplint is part of that there. But as far as I can see, there is no real maintenance going on over there. Still, in might be worth maintaining cpplint as a fork of that repository, so that changes may one day be merged back easily.

**Comment by theandrewdavis** [comment]
Ok, great, thanks for the warning! I'll get in touch with sils1297 and as you suggest I'll set up theandrewdavis/cpplint as a fork of google/styleguide. In light of that, I'll go ahead and close this PR. Cheers!
